// Export Data Modal
// Universal export modal for all data types across the platform

import React, { useState } from 'react';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';
import { Label } from '../ui/label';
import { Checkbox } from '../ui/checkbox';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../ui/select';
import { Download, FileSpreadsheet, FileText, FileJson, Calendar, Filter, CheckCircle } from 'lucide-react';
import { toast } from 'sonner';

interface ExportDataModalProps {
  isOpen: boolean;
  onClose: () => void;
  onExport: (config: ExportConfig) => void;
  dataType: 'emissions' | 'users' | 'trips' | 'policies' | 'reports' | 'audit-trail' | 'all';
  totalRecords?: number;
}

export interface ExportConfig {
  format: 'csv' | 'xlsx' | 'pdf' | 'json';
  dateRange: 'all' | 'last-7-days' | 'last-30-days' | 'last-90-days' | 'ytd' | 'custom';
  customDateStart?: string;
  customDateEnd?: string;
  includeArchived: boolean;
  columns: string[];
  filters: Record<string, any>;
}

const exportFormats = [
  { 
    value: 'csv', 
    label: 'CSV', 
    description: 'Comma-separated values for spreadsheets',
    icon: FileSpreadsheet,
    size: 'Small',
  },
  { 
    value: 'xlsx', 
    label: 'Excel (XLSX)', 
    description: 'Microsoft Excel format with formatting',
    icon: FileSpreadsheet,
    size: 'Medium',
  },
  { 
    value: 'pdf', 
    label: 'PDF', 
    description: 'Print-ready formatted document',
    icon: FileText,
    size: 'Large',
  },
  { 
    value: 'json', 
    label: 'JSON', 
    description: 'Machine-readable data format',
    icon: FileJson,
    size: 'Small',
  },
];

const dateRangeOptions = [
  { value: 'all', label: 'All Time' },
  { value: 'last-7-days', label: 'Last 7 Days' },
  { value: 'last-30-days', label: 'Last 30 Days' },
  { value: 'last-90-days', label: 'Last 90 Days' },
  { value: 'ytd', label: 'Year to Date (2026)' },
  { value: 'custom', label: 'Custom Range' },
];

const columnsByDataType = {
  emissions: [
    'Date',
    'Employee ID',
    'Employee Name',
    'Location',
    'Transport Mode',
    'Distance (km)',
    'Emissions (kg CO₂e)',
    'Data Quality',
    'Source',
    'Created At',
  ],
  users: [
    'User ID',
    'Email',
    'Full Name',
    'Role',
    'Department',
    'Location',
    'Status',
    'Created At',
    'Last Login',
  ],
  trips: [
    'Trip ID',
    'Date',
    'Driver',
    'Passengers',
    'Origin',
    'Destination',
    'Distance (km)',
    'Status',
    'Emissions Saved (kg CO₂e)',
  ],
  policies: [
    'Policy ID',
    'Policy Name',
    'Type',
    'Effective Date',
    'Expiry Date',
    'Status',
    'Applicable To',
    'Locations',
    'Created By',
  ],
  reports: [
    'Report ID',
    'Report Name',
    'Type',
    'Date Range',
    'Generated At',
    'Generated By',
    'Status',
  ],
  'audit-trail': [
    'Timestamp',
    'User',
    'Action',
    'Resource Type',
    'Resource ID',
    'Changes',
    'IP Address',
  ],
  all: [
    'All available columns',
  ],
};

export function ExportDataModal({ 
  isOpen, 
  onClose, 
  onExport, 
  dataType,
  totalRecords = 0
}: ExportDataModalProps) {
  const [format, setFormat] = useState<'csv' | 'xlsx' | 'pdf' | 'json'>('xlsx');
  const [dateRange, setDateRange] = useState<string>('last-30-days');
  const [customDateStart, setCustomDateStart] = useState('');
  const [customDateEnd, setCustomDateEnd] = useState('');
  const [includeArchived, setIncludeArchived] = useState(false);
  const [selectedColumns, setSelectedColumns] = useState<string[]>(
    columnsByDataType[dataType] || []
  );

  const availableColumns = columnsByDataType[dataType] || [];

  const toggleColumn = (column: string) => {
    if (selectedColumns.includes(column)) {
      setSelectedColumns(selectedColumns.filter(c => c !== column));
    } else {
      setSelectedColumns([...selectedColumns, column]);
    }
  };

  const selectAllColumns = () => {
    setSelectedColumns(availableColumns);
  };

  const deselectAllColumns = () => {
    setSelectedColumns([]);
  };

  const handleExport = () => {
    const config: ExportConfig = {
      format,
      dateRange,
      customDateStart: dateRange === 'custom' ? customDateStart : undefined,
      customDateEnd: dateRange === 'custom' ? customDateEnd : undefined,
      includeArchived,
      columns: selectedColumns,
      filters: {},
    };

    onExport(config);
    toast.success(`Export started in ${format.toUpperCase()} format`);
    onClose();
  };

  const estimatedRecords = includeArchived ? totalRecords + 150 : totalRecords;
  const selectedFormat = exportFormats.find(f => f.value === format);

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Download className="h-6 w-6 text-[#00bc7d]" />
            Export {dataType.charAt(0).toUpperCase() + dataType.slice(1)} Data
          </DialogTitle>
          <DialogDescription>
            Configure export settings and download your data
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-5 py-4">
          {/* Format Selection */}
          <div>
            <Label className="mb-3 block">Export Format</Label>
            <div className="grid grid-cols-2 gap-3">
              {exportFormats.map((fmt) => {
                const Icon = fmt.icon;
                return (
                  <button
                    key={fmt.value}
                    onClick={() => setFormat(fmt.value as any)}
                    className={`p-4 border-2 rounded-lg transition-all text-left ${
                      format === fmt.value
                        ? 'border-[#00bc7d] bg-green-50'
                        : 'border-gray-200 hover:border-gray-300'
                    }`}
                  >
                    <div className="flex items-center gap-3 mb-2">
                      <Icon className={`h-6 w-6 ${format === fmt.value ? 'text-[#00bc7d]' : 'text-gray-400'}`} />
                      <div className="flex-1">
                        <p className="font-semibold text-gray-900">{fmt.label}</p>
                        <Badge variant="outline" className="text-xs mt-1">
                          {fmt.size} file size
                        </Badge>
                      </div>
                    </div>
                    <p className="text-xs text-gray-600">{fmt.description}</p>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Date Range */}
          <div>
            <Label htmlFor="dateRange">
              <Calendar className="h-4 w-4 inline mr-1" />
              Date Range
            </Label>
            <Select value={dateRange} onValueChange={setDateRange}>
              <SelectTrigger id="dateRange">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {dateRangeOptions.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Custom Date Range */}
          {dateRange === 'custom' && (
            <div className="grid grid-cols-2 gap-4 p-4 bg-gray-50 rounded-lg">
              <div>
                <Label htmlFor="startDate">Start Date</Label>
                <input
                  id="startDate"
                  type="date"
                  value={customDateStart}
                  onChange={(e) => setCustomDateStart(e.target.value)}
                  className="w-full px-3 py-2 border rounded-lg"
                />
              </div>
              <div>
                <Label htmlFor="endDate">End Date</Label>
                <input
                  id="endDate"
                  type="date"
                  value={customDateEnd}
                  onChange={(e) => setCustomDateEnd(e.target.value)}
                  min={customDateStart}
                  className="w-full px-3 py-2 border rounded-lg"
                />
              </div>
            </div>
          )}

          {/* Columns Selection */}
          <div>
            <div className="flex items-center justify-between mb-3">
              <Label>
                <Filter className="h-4 w-4 inline mr-1" />
                Select Columns ({selectedColumns.length}/{availableColumns.length})
              </Label>
              <div className="flex gap-2">
                <Button
                  variant="link"
                  size="sm"
                  onClick={selectAllColumns}
                  className="h-auto p-0 text-xs"
                >
                  Select All
                </Button>
                <Button
                  variant="link"
                  size="sm"
                  onClick={deselectAllColumns}
                  className="h-auto p-0 text-xs"
                >
                  Deselect All
                </Button>
              </div>
            </div>
            <div className="max-h-48 overflow-y-auto p-4 border rounded-lg space-y-2">
              {availableColumns.map((column) => (
                <div key={column} className="flex items-center gap-2">
                  <Checkbox
                    id={`col-${column}`}
                    checked={selectedColumns.includes(column)}
                    onCheckedChange={() => toggleColumn(column)}
                  />
                  <label
                    htmlFor={`col-${column}`}
                    className="text-sm text-gray-700 cursor-pointer flex-1"
                  >
                    {column}
                  </label>
                </div>
              ))}
            </div>
          </div>

          {/* Additional Options */}
          <div className="space-y-3 p-4 bg-gray-50 rounded-lg">
            <div className="flex items-center gap-2">
              <Checkbox
                id="includeArchived"
                checked={includeArchived}
                onCheckedChange={(checked) => setIncludeArchived(checked as boolean)}
              />
              <label htmlFor="includeArchived" className="text-sm text-gray-700 cursor-pointer">
                Include archived records
              </label>
            </div>
          </div>

          {/* Export Summary */}
          <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
            <div className="flex items-start gap-2">
              <CheckCircle className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
              <div className="flex-1">
                <p className="text-sm font-medium text-blue-900 mb-2">Export Summary</p>
                <div className="space-y-1 text-xs text-blue-700">
                  <p>• Format: {selectedFormat?.label}</p>
                  <p>• Date Range: {dateRangeOptions.find(d => d.value === dateRange)?.label}</p>
                  <p>• Columns: {selectedColumns.length} selected</p>
                  <p>• Estimated Records: ~{estimatedRecords.toLocaleString()}</p>
                  <p>• File Size: ~{selectedFormat?.size}</p>
                </div>
              </div>
            </div>
          </div>

          {/* GDPR Notice */}
          <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg">
            <p className="text-xs text-amber-800">
              <strong>GDPR Notice:</strong> Exported data may contain personal information. 
              Handle in accordance with data protection policies. This export will be logged for audit purposes.
            </p>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            Cancel
          </Button>
          <Button 
            onClick={handleExport}
            disabled={selectedColumns.length === 0}
          >
            <Download className="h-4 w-4 mr-2" />
            Export Data
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
